### ISSUE TITLE
Imposible montar el volumen

### ISSUE THREAD

**Issue by JoNMii** [symbiose/symbiose#500]
Trying to login to the FTP, error shown,.
* * *
```
Webos.Error: Imposible montar el volumen

    at new WError (http://escritorio.jonmifile.com//boot/lib/error.js:10:27)
    at Function.Webos.Error.build (http://escritorio.jonmifile.com//boot/lib/error.js:118:9)
    at Function.Webos.Error.trigger (http://escritorio.jonmifile.com//boot/lib/error.js:127:37)
    at /usr/lib/nautilus/nautilus.js:244:20
    at WCallback.$_WCallback_fire [as fire] (http://escritorio.jonmifile.com//boot/lib/callback.js:67:43)
    at $_WCallback_error (http://escritorio.jonmifile.com//boot/lib/callback.js:106:15)
    at WCallback.$_WCallback_fire [as fire] (http://escritorio.jonmifile.com//boot/lib/callback.js:67:43)
    at WCallback.$_WCallback_error [as error] (http://escritorio.jonmifile.com//boot/lib/callback.js:106:15)
    at /usr/lib/webos/ftp.js:296:14
Browser : "Netscape", version : "5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36", platform : "Win32", user agent : "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"
```

**Comment by emersion** [comment]
Is it possible to have a dump of HTTP requests? (With developer tools, type `F12`)
