### ISSUE TITLE
Cannot retrieve users list

### ISSUE THREAD

**Issue by rodrigoselau** [symbiose/symbiose#512]
I can not connect with my User and password registered in ldap

Webos.Error: Cannot retrieve users list
Invalid user e-mail (empty e-mail)

    at new Webos.Error (http://192.168.20.25/symbiose//boot/lib/error.js:10:27)
    at Function.Webos.Error.build (http://192.168.20.25/symbiose//boot/lib/error.js:133:9)
    at Webos.ServerCall.Response.getError (http://192.168.20.25/symbiose//boot/lib/servercall.js:1995:23)
    at Webos.Callback.Result.triggerError (http://192.168.20.25/symbiose//boot/lib/callback.js:252:28)
    at <anonymous>:669:12
    at WCallback.$_WCallback_fire [as fire] (http://192.168.20.25/symbiose//boot/lib/callback.js:67:43)
    at $_WCallback_error (http://192.168.20.25/symbiose//boot/lib/callback.js:106:15)
    at WCallback.$_WCallback_fire [as fire] (http://192.168.20.25/symbiose//boot/lib/callback.js:67:43)
    at null.<anonymous> (http://192.168.20.25/symbiose//boot/lib/operation.js:207:15)
Browser : "Netscape", version : "5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36", platform : "Win32", user agent : "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"
```

**Comment by emersion** [comment]
You must provide a valid e-mail for each user in the LDAP database.
