### ISSUE TITLE
Cannot read property 'about' of undefined

### ISSUE THREAD

**Issue by rodrigoselau** [symbiose/symbiose#513]
Não consigo conectar ao google driver e a apikey e a clientid estão corretas
* * *
```
TypeError: Cannot read property 'about' of undefined

Stack trace :
TypeError: Cannot read property 'about' of undefined
    at getThisDirIdFn (/usr/lib/google-api/webos.js:411:36)
    at Function.Webos.GoogleDriveFile._getFileId (/usr/lib/google-api/webos.js:444:2)
    at Webos.GoogleDriveFile.contents (/usr/lib/google-api/webos.js:242:26)
    at Function.Webos.File.listDir (http://192.168.1.110/symbiose//boot/lib/file.js:781:7)
    at $.webos.widget.readDir (<anonymous>:378:11)
    at null.readDir (http://192.168.1.110/symbiose//boot/lib/jquery-ui-1.10.4.custom.min.js:6:5029)
    at $.webos.widget._create (<anonymous>:254:9)
    at null.<anonymous> (http://192.168.1.110/symbiose//boot/lib/jquery-ui-1.10.4.custom.min.js:6:5029)
    at t.isFunction.l.(anonymous function).t (http://192.168.1.110/symbiose//boot/lib/jquery-ui-1.10.4.custom.min.js:6:4854)
    at <anonymous>:88:15
Browser : "Netscape", version : "5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36", platform : "Win32", user agent : "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"
```

**Comment by emersion** [comment]
Can you speak English please? Thanks!

**Comment by rodrigoselau** [comment]
I can not seem connect to my google driver, the api key and the clientid are correct but of this error and does not connect to the driver

**Comment by emersion** [comment]
Can you open the developer console (press <kbd>F12</kbd>) and dump here all output please?

Seems that a method from the official Google Drive API has been dropped or something.
