### ISSUE TITLE
The connection failed

### ISSUE THREAD

**Issue by min4builder** [symbiose/symbiose#521]
I just set up XAMPP and logged in as 'admin', and the server refuses the connection. It seems like the path is correct, but with an extra /
* * *
```
Webos.Error: The connection failed
Cannot open data file &quot;core/users&quot; (&quot;/opt/lampp/htdocs/symbiose/symbiose/lib/dao/../../var/lib/jsondb//core/users.json&quot; : error while writing)

    at new Webos.Error (http://symbiose.localhost//boot/lib/error.js:10:27)
    at Function.Webos.Error.build (http://symbiose.localhost//boot/lib/error.js:133:9)
    at Webos.ServerCall.Response.getError (http://symbiose.localhost//boot/lib/servercall.js:1995:23)
    at Webos.Callback.Result.triggerError (http://symbiose.localhost//boot/lib/callback.js:252:28)
    at gnome-login.js:89:13
    at WCallback.$_WCallback_fire [as fire] (http://symbiose.localhost//boot/lib/callback.js:67:43)
    at $_WCallback_error (http://symbiose.localhost//boot/lib/callback.js:106:15)
    at WCallback.$_WCallback_fire [as fire] (http://symbiose.localhost//boot/lib/callback.js:67:43)
    at null.<anonymous> (http://symbiose.localhost//boot/lib/operation.js:207:15)
Browser : "Netscape", version : "5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/40.0.2214.111 Chrome/40.0.2214.111 Safari/537.36", platform : "Linux x86_64", user agent : "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/40.0.2214.111 Chrome/40.0.2214.111 Safari/537.36"
```

**Comment by emersion** [comment]
You probably didn't set the right permissions to your files. Please see the installation guide on the wiki.

(The extra / is not important)
