### ISSUE TITLE
Webos.Error [#0]: Malformed JSON data (SyntaxError): Unexpected token <. Data :  Fatal error:  Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by daliMejri** [symbiose/symbiose#522]
when u trie to  disconnect on local this error show for me 

Fatal error:  Maximum execution time of 30 seconds exceeded in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\projects\symbiose-mastersql\symbiose-master\lib\dao\localfs\LocalFs.class.php on line 245

    at api calling action "disconnect" in module "user"
    with arguments {}
    at new Webos.Error (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/error.js:10:27)
    at Function.Webos.Error.build (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/error.js:133:9)
    at Object.Webos.Callback.Result.getError (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/callback.js:242:22)
    at Object.Webos.Callback.Result.triggerError (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/callback.js:252:28)
    at gnome-logout.js:62:10
    at WCallback.$_WCallback_fire [as fire] (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/callback.js:67:43)
    at $_WCallback_error (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/callback.js:106:15)
    at WCallback.$_WCallback_fire [as fire] (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/callback.js:67:43)
    at null.<anonymous> (http://127.0.0.1/projects/symbiose-mastersql/symbiose-master//boot/lib/operation.js:207:15)

**Comment by emersion** [comment]
Duplicate
